blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'post/<int:pk>/', views.PostView.as_view(), name='detail'),
    path(r'archive/', views.archives, name='archives_page'),
    path(r'archives/<int:year>/<int:month>/', views.ArchivesView.as_view(), name='archives'),
    path(r'category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path(r'tag/<int:pk>/', views.TagView.as_view(), name='tag'),
]

blogdemo/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('search/', include('haystack.urls')),
    path('markdown/', include( 'django_markdown.urls')),
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
# from mdeditor.fields import MDTextField 
from ckeditor.fields import RichTextField 
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '文章分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=70)
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # content = MDTextField()
    content = RichTextUploadingField()
    modify_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')
    modify_date = models.DateField(auto_now=True, verbose_name='修改日期')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    created_date = models.DateField(auto_now_add=True, verbose_name='创建日期')
    summary = models.CharField(max_length=200, verbose_name='概要')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']
        verbose_name = '文章'
        verbose_name_plural = verbose_name


class Visit(models.Model):
    visit_date = models.DateField(auto_now_add=True, verbose_name='访问日期')
    count = models.IntegerField(default=0, verbose_name='日访问量')
    
    class Meta:
        verbose_name = '日访问量'
        verbose_name_plural = verbose_name
        
    def __str__(self):
        return str(self.day)

    def sum_over(self):
        return 

blog/views.py
import markdown
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

#from comments.forms import CommentForm
from .models import Post, Category, Tag
from .visit_record import record_visit


def archives(request):
    date_list = Post.objects.dates('created_time', 'month', order='DESC')
    return render(request, 'archives.html', context={'date_list': date_list})


class IndexView(ListView):
    model = Post
    template_name = 'index.html'
    context_object_name = 'post_list'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        record_visit()
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        next = 0
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range
        if page_number == 1:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        if page_number < total_pages:
            next = page_number + 1
        else:
            next = total_pages
        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'next': next,
        }

        return data

class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month)

    def get_context_data(self, **kwargs):
        context = super(ArchivesView, self).get_context_data(**kwargs)
        # title = '{} å¹´ {} æœˆ'.format(self.kwargs.get('year'), self.kwargs.get('month'))
        title = '{}年{}月'.format(self.kwargs.get('year'), self.kwargs.get('month'))
        context.update({
            'title': title
        })
        return context


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        title = '{}'.format(get_object_or_404(Category, pk=self.kwargs.get('pk')))
        context.update({
            'title': title
        })
        return context


class TagView(IndexView):
    def get_queryset(self):
        ta = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=ta)

    def get_context_data(self, **kwargs):
        context = super(TagView, self).get_context_data(**kwargs)
        title = '{}'.format(get_object_or_404(Tag, pk=self.kwargs.get('pk')))
        context.update({
            'title': title
        })
        return context


class PostView(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        # markdown
        post = super(PostView, self).get_object(queryset=None)
        post.content = markdown.markdown(post.content,
                                        extensions=[
                                            'markdown.extensions.extra',
                                            'markdown.extensions.codehilite',
                                            'markdown.extensions.toc',
                                        ])
        return post

    # def get_context_data(self, **kwargs):
    #     # form and comment_list
    #     context = super(PostView, self).get_context_data(**kwargs)
    #     form = CommentForm()
    #     comment_list = self.object.comment_set.all()
    #     context.update({
    #         'form': form,
    #         'comment_list': comment_list,
    #     })
    #     return context

templates/archives.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}
<!-- Blog Entries Column -->
<div class="col-md-9">

  <h1 class="my-4">Archives</h1>

  <!-- Blog Post -->
  <ul class="list-group">
    {% for date in date_list %}
      <li class="list-group-item ">
          <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month}} 月</a>
      </li>
    {% empty %}
    <li class="list-group-item ">
      Not Available
    </li>
    {% endfor %}
    </ul>

</div>
{% endblock main %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="zh-CN" class=" no-touch">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Infernoid's Infinity</title>
	<link rel="stylesheet" id="toc-screen-css" href="{% static 'blog/wp-content/css/screen.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" id="xmag-fonts-css" href="{% static 'blog/wp-content/css/google_font.css' %}" type="text/css" media="all">
	<link rel="stylesheet" id="xmag-icons-css" href="{% static 'blog/wp-content/css/simple-line-icons.css' %}" type="text/css" media="all">
	<link rel="stylesheet" id="xmag-style-css" href="{% static 'blog/wp-content/css/style.min.css' %}" type="text/css" media="all">
	<style id="xmag-style-inline-css" type="text/css">
		.main-navbar {
			background-color: #fff;
			border-top: 1px solid #eee;
			border-bottom: 1px solid #eee;
			-webkit-box-shadow: 0 3px 2px 0 rgba(0, 0, 0, 0.03);
			box-shadow: 0 3px 2px 0 rgba(0, 0, 0, 0.03);
		}

		.main-menu>li>a,
		.main-navigation .home-link a {
			color: #333;
			border-left: 1px solid #f2f2f2;
		}

		.main-menu>li:last-child>a {
			border-right: 1px solid #f2f2f2;
		}

		.main-menu>li>a:hover,
		.main-navigation .home-link a:hover {
			background-color: #fff;
			color: ;
		}

		.main-navigation .home-link a:hover:before,
		.main-menu>li:hover:before,
		.main-menu>li:active:before,
		.main-menu>li.current_page_item:before,
		.main-menu>li.current-menu-item:before {
			content: '';
			position: absolute;
			bottom: 0;
			left: 0;
			display: block;
			width: 100%;
			height: 2px;
			z-index: 2;
			background-color: ;
		}

		.main-menu ul {
			background-color: #fff;
			border: 1px solid #eee;
		}

		.main-menu ul a {
			border-top: 1px solid #f2f2f2;
			color: #555;
		}

		.main-menu ul a:hover {
			color: ;
		}

		#mobile-header {
			background-color: #fff;
			border-bottom: 1px solid #eee;
			-webkit-box-shadow: 0 3px 2px 0 rgba(0, 0, 0, 0.03);
			box-shadow: 0 3px 2px 0 rgba(0, 0, 0, 0.03);
		}

		#mobile-header .mobile-title,
		#mobile-header .mobile-menu-toggle {
			color: #333;
		}

		.button-toggle,
		.button-toggle:before,
		.button-toggle:after {
			background-color: #333;
		}

		span.highlighted {
            color: red;
        }
	</style>
	<!-- <script type="text/javascript" src="http://blog.codingplayboy.com/wp-includes/js/jquery/jquery.js?ver=1.12.4"></script> -->
	<script type="text/javascript" src="http://blog.codingplayboy.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1"></script>
	<link rel="icon" href="{% static 'blog/img/icon.jpg' %}" sizes="32x32">
	<!-- <link rel="icon" href="http://blog.codingplayboy.com/wp-content/uploads/2016/06/cropped-profile-192x192.jpg" sizes="192x192"> -->
	<!-- <link rel="apple-touch-icon-precomposed" href="http://blog.codingplayboy.com/wp-content/uploads/2016/06/cropped-profile-180x180.jpg"> -->
	<!-- <meta name="msapplication-TileImage" content="http://blog.codingplayboy.com/wp-content/uploads/2016/06/cropped-profile-270x270.jpg"> -->
</head>

<body class="home blog site-fullwidth layout2">

	<div id="page" class="hfeed site">

		<a class="skip-link screen-reader-text" href="#">Skip to content</a>

		<header id="masthead" class="site-header" role="banner">

			<div class="header-top collapse">
				<div class="container">
					<div class="row">
						<div class="col-4">
							<div class="site-branding">
								<h1 class="site-title"><a href="" rel="home">Infernoid's Infinity</a></h1>
							</div><!-- .site-branding -->
						</div>
						<div class="col-8">
							<div class="header-navigation">

								<div class="search-top">
									<form role="search" method="get" class="search-form" action="{% url 'haystack_search' %}">
										<label>
											<span class="screen-reader-text">Search for:</span>
											<input type="search" class="search-field" placeholder="Search …" value="" name="q">
										</label>
										<button type="submit" class="search-submit">
											<span class="sli icon-magnifier"></span>
											<span class="screen-reader-text">Search</span>
										</button>
									</form>
                                </div>
                                
								<!-- Search Form -->
								<nav id="top-navigation" class="top-navigation" role="navigation">
									<ul id="menu-%e9%a1%b5%e9%9d%a2" class="top-menu">
										<!-- <li id="menu-item-694" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-694">
                                            <a href="#">技术</a>
                                        </li>
										<li id="menu-item-651" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-651">
                                            <a href="#">读书</a>
                                        </li> -->
									</ul>
                                </nav><!-- #top-navigation -->
                                
							</div>
						</div>
					</div><!-- .row -->
				</div>
			</div><!-- Header Top -->


			<nav id="main-navbar" class="main-navbar">
				<div class="container">
					<div id="main-navigation" class="main-navigation">
						<div class="home-link">
							<a href="/" title="HOME" rel="home"><span class="icon-home"></span></a>
						</div>

						<ul id="menu-%e5%af%bc%e8%88%aa" class="main-menu">
							<li id="menu-item-615" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-615">
								<a href="">DATABASE</a>
								<ul class="sub-menu">
									<li id="menu-item-605" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-605">
                                        <a href="{% url 'blog:category' 1 %}">MySQL</a>
                                    </li>
                                    <li id="menu-item-605" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-605">
                                        <a href="{% url 'blog:category' 2 %}">SQL Server</a>
                                    </li>
                                    <li id="menu-item-605" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-605">
                                        <a href="{% url 'blog:category' 3 %}">Oracle</a>
                                    </li>
                                    <li id="menu-item-605" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-605">
                                        <a href="{% url 'blog:category' 4 %}">PostgreSQL</a>
                                    </li>
								</ul>
							</li>
							<li id="menu-item-603" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-603">
								<a href="">PYTHON</a>
								<ul class="sub-menu">
									<li id="menu-item-607" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-607">
                                        <a href="{% url 'blog:category' 5 %}">Django</a>
                                    </li>
                                    <li id="menu-item-607" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-607">
                                        <a href="{% url 'blog:category' 6 %}">Flask</a>
                                    </li>
                                    <li id="menu-item-607" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-607">
                                        <a href="{% url 'blog:category' 7 %}">Superset</a>
                                    </li>
                                    <li id="menu-item-607" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-607">
                                        <a href="{% url 'blog:category' 8 %}">crawler</a>
                                    </li>
                                    <li id="menu-item-607" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-607">
                                        <a href="{% url 'blog:category' 9 %}">Tkinter</a>
                                    </li>
								</ul>
							</li>
							<li id="menu-item-602" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-602">
                                <a href="">JAVA</a>
                                <ul class="sub-menu">
                                    <li id="menu-item-607" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-607">
                                        <a href="{% url 'blog:category' 10 %}">Spring Boot</a>
                                    </li>
								</ul>
                            </li>
							<li id="menu-item-613" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-613">
								<a href="">JAVASCRIPT</a>
								<ul class="sub-menu">
									<li id="menu-item-872" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-872">
                                        <a href="{% url 'blog:category' 11 %}">Vue</a>
                                    </li>
								</ul>
							</li>
							<li id="menu-item-616" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-616">
								<a href="">MORE</a>
								<ul class="sub-menu">
									<li id="menu-item-609" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-609">
                                        <a href="{% url 'blog:category' 12 %}">Airflow</a>
                                    </li>
									<li id="menu-item-786" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-786">
                                        <a href="{% url 'blog:category' 13 %}">kettle</a>
                                    </li>
                                    <li id="menu-item-786" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-786">
                                        <a href="{% url 'blog:category' 14 %}">SSIS</a>
                                    </li>
									<li id="menu-item-611" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-611">
                                        <a href="{% url 'blog:category' 15 %}">Shell</a>
									</li>
									<li id="menu-item-611" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-611">
										<a href="{% url 'blog:category' 16 %}">Others</a>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</nav><!-- Main Navbar -->

        </header><!-- #masthead -->
        
        <div id="content" class="site-content">
            <div class="container">

                {% block main %}
                {% endblock main %}

				{% block side %}
				{% endblock side %}

            </div><!-- .container -->
        </div><!-- #content -->

        <footer id="colophon" class="site-footer" role="contentinfo">

            <div class="footer widget-area" role="complementary">
                <div class="container">
                    <div class="row">
                        <div class="col-4" id="footer-area-left">
                        </div>
                        <div class="col-4" id="footer-area-center">
                        </div>
                        <div class="col-4" id="footer-area-right">
                        </div>
                    </div><!-- .row -->
                </div>
            </div>

            <div class="footer-copy">
                <div class="container">
                    <div class="row">
						<div class="col-3"></div>
                        <div class="col-6">
                            <div class="site-info">© 2019 
								<span class="sep">/</span>
								<span class="sep">Infernoid's Infinity</span>
								<span class="sep">/</span>
								<a class="sep" href="http://www.beian.miit.gov.cn">粤ICP备19031989号</a>
							</div>
                        </div>
                        <div class="col-3"></div>
                    </div><!-- .row -->
                </div>
            </div>

        </footer><!-- #colophon -->

        <a href="#" id="scroll-up" style="display: none;"><span class="icon-arrow-up"></span></a>
    </div><!-- #page -->

</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}
<div id="primary" class="content-area">
	<main id="main" class="site-main" role="main">
		
		<div class="posts-loop">
            {% for post in post_list %}
			<article id="post-1029" class="list-post post-1029 post type-post status-publish format-standard hentry category-js tag-javascript tag-macro-task tag-micro-task tag-promise tag-settimeout tag-task-queue tag-async">
				<header class="entry-header">
					<div class="entry-meta">
						<span class="posted-on">{{ post.created_date }}</span>
						<span class="sep"></span>
						<span class="category">
                            {% for tag in post.tags.all %}
                            <a href="#" rel="category tag">{{ tag.name }}</a>
                            {% endfor %}
                        </span>
					</div>
					<h2 class="entry-title"><a href="{{ post.get_absolute_url }}" rel="bookmark">{{ post.title }}</a></h2>
				</header><!-- .entry-header -->
				<div class="entry-summary">
					<p>{{ post.summary }}</p>
				</div><!-- .entry-summary -->
			</article><!-- #post-## -->
            {% endfor %}
		</div><!-- / .posts-loop -->

		<nav class="navigation pagination" role="navigation">
			{% if is_paginated %}
			<div class="nav-links">
				{% if first %}
				<a class="page-numbers" href="?page=1">1</a>
				{% endif %}
				{% if left %}
					{% if left_has_more %}
					<span class="page-numbers dots">…</span>
					{% endif %}
					{% for i in left %}
					<a class="page-numbers" href="?page={{ i }}">{{ i }}</a>
					{% endfor %}
				{% endif %}
				<a aria-current="page" class="page-numbers current">{{ page_obj.number }}</a>
				{% if right %}
					{% for i in right %}
					<a class="page-numbers" href="?page={{ i }}">{{ i }}</a>
					{% endfor %}
					{% if right_has_more %}
        			<span class="page-numbers dots">…</span>
					{% endif %}
				{% endif %}
				{% if last %}
				<a class="page-numbers" href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
				{% endif %}
				<a class="next page-numbers" href="?page={{ next }}">→</a>
			</div>
			{% endif %}
		</nav>

	</main><!-- #main -->
</div><!-- #primary -->
{% endblock main %}

{% block side %}
<div id="secondary" class="sidebar widget-area  widget-grey" role="complementary">

	<aside id="tag_cloud-5" class="widget widget_tag_cloud">
		<h3 class="widget-title">
			<span>标签</span>
		</h3>
		{% tag_list as t_list %}
		<div class="tagcloud">
			{% for tag in t_list %}
			<a href="{% url 'blog:tag' tag.pk %}" class="tag-cloud-link tag-link-12 tag-link-position-1" style="font-size: 10.082644628099pt;" aria-label="algorithm (2个项目)">{{ tag.name }}</a>
			{% endfor %}
		</div>
	</aside>

	<aside id="archives-5" class="widget widget_archive">
		<h3 class="widget-title"><span>文章归档</span></h3>
		<label class="screen-reader-text" for="archives-dropdown-5">文章归档</label>
		<select id="archives-dropdown-5" name="archive-dropdown" onchange="document.location.href=this.options[this.selectedIndex].value;">
			{% archives as date_list %}
			<option value="">选择月份</option>
			{% for date in date_list %}
			<option value="{% url 'blog:archives' date.year date.month %}"> {{ date.year }}年{{ date.month }}月</option>
			{% endfor %}
		</select>
	</aside>

	<aside id="wpstatistics_widget-6" class="widget widget_wpstatistics_widget">
		<h3 class="widget-title"><span>访问</span></h3>
		<ul>
			<li>今日访问: {% dayly_count %}</li>
			<li>累计访问: {% total_count %}</li>
			<!-- <li>累计访客: 0</li> -->
			<li>总计文章: {% pos_num %}</li>
			<!-- <li>最后发表日期: 2018-08-13</li> -->
		</ul>
	</aside>
	
</div><!-- #secondary .widget-area -->
{% endblock side %}

templates/post.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}
<div id="primary" class="content-area">
	<!-- <main id="main" class="site-main" role="main"> -->
	<main id="" class="" role="">

		<article id="post-1029" class="post-1029 post type-post status-publish format-standard hentry category-js tag-javascript tag-macro-task tag-micro-task tag-promise tag-settimeout tag-task-queue tag-async">

			<header class="entry-header">
				<h1 class="entry-title">{{ post.title }}</h1>
				<div class="entry-meta">
					<span class="posted-on">
						<span class="icon-clock"></span>
						<a href="http://blog.codingplayboy.com/2018/08/12/js_settimeout_promise/" rel="bookmark">
							<time class="entry-date published" datetime="2018-08-12T23:45:27+00:00">{{ post.created_time }}</time>
						</a>
					</span>
				</div>
			</header><!-- .entry-header -->

			<div class="entry-content">
			{{ post.content|safe }}
			</div><!-- .entry-content -->

		</article><!-- #post-## -->

	</main><!-- #main -->
</div><!-- #primary -->
{% endblock main %}

{% block side %}
<div id="secondary" class="sidebar widget-area  widget-grey" role="complementary">

	<aside id="tag_cloud-5" class="widget widget_tag_cloud">
		<h3 class="widget-title">
			<span>标签</span>
		</h3>
		<div class="tagcloud">
			{% for tag in post.tags.all %}
			<a href="#" class="tag-cloud-link tag-link-12 tag-link-position-1" style="font-size: 10.082644628099pt;" aria-label="algorithm (2???)">{{ tag.name }}</a>
			{% endfor %}
		</div>
	</aside>

	<aside id="archives-5" class="widget widget_archive">
		<h3 class="widget-title"><span>文章归档</span></h3>
		<label class="screen-reader-text" for="archives-dropdown-5">文章归档</label>
		<select id="archives-dropdown-5" name="archive-dropdown" onchange="document.location.href=this.options[this.selectedIndex].value;">
			{% archives as date_list %}
			<option value="">选择月份</option>
			{% for date in date_list %}
			<option value="{% url 'blog:archives' date.year date.month %}"> {{ date.year }}年{{ date.month }}月</option>
			{% endfor %}
		</select>
	</aside>

	</div><!-- #secondary .widget-area -->
{% endblock side %}